version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: update-npm 
          command: 'sudo npm install -g npm@latest'
      - run:
          name: update-dependencies
          command: 'npm install'
      - run:
          name: Test
          command: |
            node --version
            npm --version
