version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: $CIRCLE_WORKING_DIRECTORY/CircleCiDemo
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: update-npm 
          command: |
            pwd
            sudo npm install -g npm@latest
      - run:
          name: update-dependencies
          command: 'npm install'
      - run:
          name: Build
          command: |
            node --version
            npm --version
            npm test
