version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: update-npm 
          command: 'sudo npm install -g npm@latest'
      - run:
          name: update-dependencies
          command: 'npm install'
      - run:
          name: Build
          command: |
            node --version
            npm --version
            npm test
    test:
      docker:
        - image: circleci/node
      steps:
        - checkout
        - run:
            name: Test
            command: |
              npm --version  

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test


