version: 2
general:
  branches:
    only:
     - master
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: update-npm 
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Test
          command: 'npm test'
